version: '3.8'
services:
  easy-english-db:
    image: postgres:latest
    container_name: easy-english-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: EasyEnglish
    ports:
      - "5432:5432"
    volumes:
      - easy-english-data:/var/lib/postgresql
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "82:80"
    depends_on:
      - easy-english-db
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - pgnetwork

volumes:
  easy-english-data:

networks:
  pgnetwork:
    driver: bridge