version: '3.8'
services:
  easy-english-db:
    image: postgres:17.2
    container_name: easy-english-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: EasyEnglish
    ports:
      - "5432:5432"
    volumes:
      - easy-english-data:/var/lib/postgresql
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "82:80"
    depends_on:
      - easy-english-db
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - pgnetwork

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000" # File browser (API)
      - "9001:9001" # Web console
    command: server /data --console-address ":9001"
    restart: unless-stopped
    volumes:
      - minio-data:/data
    networks:
      - pgnetwork

volumes:
  easy-english-data:
  minio-data:

networks:
  pgnetwork:
    driver: bridge
