@startuml
left to right direction

' Define Actors
actor Admin as A

rectangle "Easy English System" {

  ' Common functionalities
  A --> (UC_002. Đăng nhập)
  A --> (UC_003. Quên mật khẩu)
  A --> (UC_004. Xem thông báo)

  ' Use cases for Admin
  A --> (UC_025. Duyệt khóa học)
  A --> (UC_026. Quản lý người dùng)

}
@enduml