@startuml
title Gửi lại OTP

actor Guest
boundary OtpValidationView
control AuthController
control OTPService
control EmailService

autonumber

Guest -> OtpValidationView : Ấn vào nút "Resend OTP"
activate OtpValidationView
OtpValidationView -> AuthController : resendOTP(usernameOrEmail)
activate AuthController
AuthController -> OTPService : resendOTPToActiveAccount(usernameOrEmail)
activate OTPService
OTPService -> EmailService : sendOtpToActiveAccount(email, otp)
activate EmailService
EmailService -> Guest : sendEmail(otp)
deactivate EmailService
deactivate OTPService
deactivate AuthController
deactivate OtpValidationView

@enduml
