@startuml
'https://plantuml.com/sequence-diagram

title Đăng nhập với Google

autonumber

actor User
boundary LoginView
boundary HomeView
control AuthController
control AuthService
control GoogleAuthService
entity UserModel
database Database

User -> LoginView : Ấn vào "Sign in with Google"
    LoginView -> AuthController : loginWithGoogle(credential)
    AuthController -> AuthService: loginWithGoogle(credential)
    activate AuthService
    AuthService -> GoogleAuthService: verifyToken()
    activate GoogleAuthService
    GoogleAuthService --> AuthService: return payload
    AuthService -> GoogleAuthService: getInfor(payload)
    GoogleAuthService --> AuthService: return registerRequest
    deactivate GoogleAuthService
    AuthService -> UserModel : findByEmail(email)
    activate UserModel
    UserModel -> Database : findByEmail(email)
    activate Database
    Database --> UserModel : return user
    deactivate Database
    UserModel --> AuthService : return user
    deactivate UserModel
    deactivate AuthService
    deactivate AuthController
    deactivate LoginView
@enduml