@startuml
title Xem giỏ hàng

autonumber

actor User
boundary CartIcon
boundary CartView
control CartController
control CartService
entity CartModel
database Database

User -> CartIcon : Ấn vào biểu tượng giỏ hàng
activate CartIcon
CartIcon -> CartView : navigate()
deactivate CartIcon
activate CartView

CartView -> CartController : getCart()
activate CartController
CartController -> CartService : getCartByUsername(username)
activate CartService
CartService -> CartModel : findByUsername(username)
activate CartModel
CartModel -> Database : findByUsername(username)
activate Database
Database --> CartModel : return cart
deactivate Database
CartModel --> CartService : return cart
deactivate CartModel
CartService --> CartController : return cart
deactivate CartService
CartController --> CartView : return cart
deactivate CartController

CartView -> CartView : Hiển thị giỏ hàng
deactivate CartView

@enduml
